name: Monitor Script Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'monitor.sh'
      - 'log_monitor/**'
      - '.github/workflows/monitor.yml'

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Validate AWS identity
        run: aws sts get-caller-identity

      - name: Run monitor script
        run: |
          chmod +x monitor.sh
          ./monitor.sh

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitor-logs
          path: log_monitor/*.log
